services:
  oasipdb:
    container_name: oasipdb
    image: mysql
    restart: always
    ports:
      - "3366:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=us1t2pproject"
    volumes:
      - ./data/oasip-new-data.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data/my.cnf:/etc/mysql/conf.d/custom.cnf
  oasipbackend:
    container_name: oasipbackend
    build: ./backend
    restart: always
    image: backend
    ports:
      - "8080:8080"
    links:
      - oasipdb

  oasipfrontend:
    container_name: oasipfrontend
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "80:80"
