services:
  oasipdb:
    container_name: oasipdb
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=us1t2pproject"
    volumes:
      - ./data/oasip-create-insert.sql:/docker-entrypoint-initdb.d/setup.sql
  oasipbackend:
    container_name: oasipbackend
    build: ./backend
    restart: always
    image: backend
    ports:
      - "8080:8080"
    links:
      - oasipdb
    
  
