# This is a basic workflow to help you get started with Actions

name: bulid_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: compose down delete image
        run: |
          docker-compose rm -svf oasipfrontend oasipbackend oasipproxy
      - name: tag and push registry image
        run: |
          docker build -t backend ./backend
          docker tag backend rabmeat/oasip-us1-backend
          docker push rabmeat/oasip-us1-backend
          docker build -t frontend ./frontend
          docker tag frontend rabmeat/oasip-us1-frontend
          docker push rabmeat/oasip-us1-frontend
          
      # Runs a set of commands using the runners shell
      - name: build and deploy
        run: |
          docker-compose up -d
          docker rmi $(docker images -f "dangling=true" -q) --force
